// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/movies.proto

package movies

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Movies service

func NewMoviesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Movies service

type MoviesService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Movies_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Movies_PingPongService, error)
	GetMovieByID(ctx context.Context, in *GetMovieByRequest, opts ...client.CallOption) (*MovieData, error)
	SearchMovie(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type moviesService struct {
	c    client.Client
	name string
}

func NewMoviesService(name string, c client.Client) MoviesService {
	return &moviesService{
		c:    c,
		name: name,
	}
}

func (c *moviesService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Movies.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Movies_StreamService, error) {
	req := c.c.NewRequest(c.name, "Movies.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &moviesServiceStream{stream}, nil
}

type Movies_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type moviesServiceStream struct {
	stream client.Stream
}

func (x *moviesServiceStream) Close() error {
	return x.stream.Close()
}

func (x *moviesServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *moviesServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *moviesServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *moviesServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moviesService) PingPong(ctx context.Context, opts ...client.CallOption) (Movies_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Movies.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &moviesServicePingPong{stream}, nil
}

type Movies_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type moviesServicePingPong struct {
	stream client.Stream
}

func (x *moviesServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *moviesServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *moviesServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *moviesServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *moviesServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *moviesServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moviesService) GetMovieByID(ctx context.Context, in *GetMovieByRequest, opts ...client.CallOption) (*MovieData, error) {
	req := c.c.NewRequest(c.name, "Movies.GetMovieByID", in)
	out := new(MovieData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesService) SearchMovie(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.name, "Movies.SearchMovie", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Movies service

type MoviesHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Movies_StreamStream) error
	PingPong(context.Context, Movies_PingPongStream) error
	GetMovieByID(context.Context, *GetMovieByRequest, *MovieData) error
	SearchMovie(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterMoviesHandler(s server.Server, hdlr MoviesHandler, opts ...server.HandlerOption) error {
	type movies interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
		GetMovieByID(ctx context.Context, in *GetMovieByRequest, out *MovieData) error
		SearchMovie(ctx context.Context, in *SearchRequest, out *SearchResponse) error
	}
	type Movies struct {
		movies
	}
	h := &moviesHandler{hdlr}
	return s.Handle(s.NewHandler(&Movies{h}, opts...))
}

type moviesHandler struct {
	MoviesHandler
}

func (h *moviesHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MoviesHandler.Call(ctx, in, out)
}

func (h *moviesHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MoviesHandler.Stream(ctx, m, &moviesStreamStream{stream})
}

type Movies_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type moviesStreamStream struct {
	stream server.Stream
}

func (x *moviesStreamStream) Close() error {
	return x.stream.Close()
}

func (x *moviesStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *moviesStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *moviesStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *moviesStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *moviesHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MoviesHandler.PingPong(ctx, &moviesPingPongStream{stream})
}

type Movies_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type moviesPingPongStream struct {
	stream server.Stream
}

func (x *moviesPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *moviesPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *moviesPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *moviesPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *moviesPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *moviesPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *moviesHandler) GetMovieByID(ctx context.Context, in *GetMovieByRequest, out *MovieData) error {
	return h.MoviesHandler.GetMovieByID(ctx, in, out)
}

func (h *moviesHandler) SearchMovie(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.MoviesHandler.SearchMovie(ctx, in, out)
}
